require("dotenv").config();


const PORT = process.env.PORT || 3000;
const MONGO_URL = process.env.MONGO_URL;
const COMPASS_URL = process.env.COMPASS_URL;
const AWS_S3_ACCESS_KEY = process.env.AWS_S3_ACCESS_KEY;
const AWS_S3_SECRET_KEY = process.env.AWS_S3_SECRET_KEY;
const AWS_REGION = process.env.AWS_REGION;
const AWS_BUCKET_NAME = process.env.AWS_BUCKET_NAME;
const JWT_SECRET = process.env.JWT_SECRET_KEY || process.env.JWT_SECRET;
const NODE_ENV = process.env.NODE_ENV;
const DEFAULT_ADMIN_EMAIL = process.env.DEFAULT_ADMIN_EMAIL;
const DEFAULT_ADMIN_PASSWORD = process.env.DEFAULT_ADMIN_PASSWORD;
const DEFAULT_ADMIN_PHONE = process.env.DEFAULT_ADMIN_PHONE;
const REFRESH_SECRET = process.env.REFRESH_SECRET;
const TWILIO_SID = process.env.TWILIO_SID;
const TWILIO_AUTHTOKEN = process.env.TWILIO_AUTHTOKEN;
const TWILIO_SIRVICEID = process.env.TWILIO_SIRVICEID;
const WHATSAPP_TOKEN = process.env.WHATSAPP_TOKEN;
const PHONE_NUMBER_ID = process.env.PHONE_NUMBER_ID;
const EMAIL_USER_ID = process.env.EMAIL_USER_ID;
const EMAIL_PASSWORD_ID = process.env.EMAIL_PASSWORD_ID;
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const FIREBASE_KEY_PATH = process.env.FIREBASE_KEY_PATH;

const WHAT_MESSAGE_SECRET = process.env.WHAT_MESSAGE_SECRET;
module.exports = {
    PORT,
    MONGO_URL,
    COMPASS_URL,
    AWS_S3_ACCESS_KEY,
    AWS_S3_SECRET_KEY,
    AWS_REGION,
    AWS_BUCKET_NAME,
    JWT_SECRET,
    NODE_ENV,
    DEFAULT_ADMIN_EMAIL,
    DEFAULT_ADMIN_PASSWORD,
    DEFAULT_ADMIN_PHONE,
    REFRESH_SECRET,
    TWILIO_SID,
    TWILIO_AUTHTOKEN,
    TWILIO_SIRVICEID,
    WHATSAPP_TOKEN,
    PHONE_NUMBER_ID,
    EMAIL_USER_ID,
    EMAIL_PASSWORD_ID,
    GEMINI_API_KEY,

    WHAT_MESSAGE_SECRET,
    FIREBASE_KEY_PATH

}